#pragma once

#define FILE_DEVICE_INVERTED 0xCF54

#define IOCTL_KEYBOARDFILTER_GETKEYBOARDSLENGTH CTL_CODE(FILE_DEVICE_INVERTED, 2051, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_KEYBOARDFILTER_GETKEYBOARDS CTL_CODE(FILE_DEVICE_INVERTED, 2052, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_KEYBOARDFILTER_ADDMACRO CTL_CODE(FILE_DEVICE_INVERTED, 2053, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_KEYBOARDFILTER_ISMACRO CTL_CODE(FILE_DEVICE_INVERTED, 2054, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_KEYBOARDFILTER_DELETEMACRO CTL_CODE(FILE_DEVICE_INVERTED, 2055, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_KEYBOARDFILTER_GETMACRO CTL_CODE(FILE_DEVICE_INVERTED, 2056, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_KEYBOARDFILTER_GETMACROLENGTH CTL_CODE(FILE_DEVICE_INVERTED, 2057, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_KEYBOARDFILTER_IDENTIFYKEY CTL_CODE(FILE_DEVICE_INVERTED, 2058, METHOD_BUFFERED, FILE_ANY_ACCESS)
